services:
  - type: web
    name: caldotcom-proxy
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: CAL_API_KEY
        sync: false
