services:
  - type: web
    name: caldotcom-proxy
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CAL_API_KEY
        sync: false
